<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

class GrandConference_Templates_Source extends Elementor\TemplateLibrary\Source_Base {

	/**
	 * Template prefix
	 *
	 * @var string
	 */
	protected $template_prefix = 'grandconference_';

	/**
	 * Return templates prefix
	 *
	 * @return [type] [description]
	 */
	public function get_prefix() {
		return $this->template_prefix;
	}

	public function get_id() {
		return 'grandconference-templates';
	}

	public function get_title() {
		return __( 'GrandConference Templates', 'grandconference-elementor' );
	}

	public function register_data() {}

	public function get_items( $args = array() ) {
		
		$templates = array();

		$templates_data = array(
			1 	=> array(
				'template_id'      	=> $this->template_prefix .'1',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Home 1',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_1.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/',
			),
			2 	=> array(
				'template_id'      	=> $this->template_prefix .'2',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Home 2',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_2.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/home-2/',
			),
			3 	=> array(
				'template_id'      	=> $this->template_prefix .'3',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Home 3',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_3.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/home-3/',
			),
			4 	=> array(
				'template_id'      	=> $this->template_prefix .'4',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Home 4',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_4.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/home-4/',
			),
			5 	=> array(
				'template_id'      	=> $this->template_prefix .'5',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Home 5 Business Forum',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_5.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/home-5-business-forum/',
			),
			6 	=> array(
				'template_id'      	=> $this->template_prefix .'6',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_6.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/',
			),
			7 	=> array(
				'template_id'      	=> $this->template_prefix .'7',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_7.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/',
			),
			8 	=> array(
				'template_id'      	=> $this->template_prefix .'8',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Tech Forum',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_8.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/grandtech/',
			),
			9 	=> array(
				'template_id'      	=> $this->template_prefix .'9',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Digital Event',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_9.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/digital/',
			),
			10 	=> array(
				'template_id'      	=> $this->template_prefix .'10',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Business Event',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_10.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/business/',
			),
			11 	=> array(
				'template_id'      	=> $this->template_prefix .'11',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Conference',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_11.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/design/',
			),
			12 	=> array(
				'template_id'      	=> $this->template_prefix .'12',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Awards',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_12.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/awards/',
			),
			13 	=> array(
				'template_id'      	=> $this->template_prefix .'13',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Classi About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_13.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/about-the-event/',
			),
			14 	=> array(
				'template_id'      	=> $this->template_prefix .'14',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Buy Tickets',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_14.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('tickets'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/buy-tickets/',
			),
			15 	=> array(
				'template_id'      	=> $this->template_prefix .'15',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Venue',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_15.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('venue'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/venue/',
			),
			16 	=> array(
				'template_id'      	=> $this->template_prefix .'16',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Contact Us',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_16.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/contact-us/',
			),
			17 	=> array(
				'template_id'      	=> $this->template_prefix .'17',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Schedule Fillwidth',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_17.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('schedule'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/schedule-fullwidth/',
			),
			18 	=> array(
				'template_id'      	=> $this->template_prefix .'18',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Schedule Sidebar',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_18.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('schedule'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/schedule-sidebar/',
			),
			19 	=> array(
				'template_id'      	=> $this->template_prefix .'19',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Schedule Tab',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_19.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('schedule'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/schedule-tab/',
			),
			20 	=> array(
				'template_id'      	=> $this->template_prefix .'20',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Speaker Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_20.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('speaker'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/speaker-grid/',
			),
			21 	=> array(
				'template_id'      	=> $this->template_prefix .'21',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Speaker Classic',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_21.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('speaker'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/speaker-classic/',
			),
			22 	=> array(
				'template_id'      	=> $this->template_prefix .'22',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_22.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/about',
			),
			23 	=> array(
				'template_id'      	=> $this->template_prefix .'23',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Schedules',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_23.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('schedules'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/schedules/',
			),
			24 	=> array(
				'template_id'      	=> $this->template_prefix .'24',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Artists',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_24.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('artists'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/artists/',
			),
			25 	=> array(
				'template_id'      	=> $this->template_prefix .'25',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Location',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_25.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('location'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/location/',
			),
			26 	=> array(
				'template_id'      	=> $this->template_prefix .'26',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Tickets',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_26.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('tickets'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/tickets/',
			),
			27 	=> array(
				'template_id'      	=> $this->template_prefix .'27',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event | About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_27.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/about/',
			),
			28 	=> array(
				'template_id'      	=> $this->template_prefix .'28',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event | Schedules',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_28.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('schedules'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/schedules/',
			),
			29 	=> array(
				'template_id'      	=> $this->template_prefix .'29',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event | Speakers',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_29.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('speakers'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/speakers/',
			),
			30 	=> array(
				'template_id'      	=> $this->template_prefix .'30',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Conference | About',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_30.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('about'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/design/about/',
			),
			31 	=> array(
				'template_id'      	=> $this->template_prefix .'31',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Awards | Speakers',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_31.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('speakers'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/awards/speakers/',
			),
			/*32 	=> array(
				'template_id'      	=> $this->template_prefix .'32',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Single Portfolio 1',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_32.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/single-portfolio-1/',
			),
			33 	=> array(
				'template_id'      	=> $this->template_prefix .'33',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Single Portfolio 2',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_33.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/single-portfolio-2/',
			),
			34 	=> array(
				'template_id'      	=> $this->template_prefix .'34',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Single Portfolio 3',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_34.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/single-portfolio-3/',
			),
			35 	=> array(
				'template_id'      	=> $this->template_prefix .'35',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Single Portfolio 4',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_35.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('portfolio'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/single-portfolio-4/',
			),*/
			36 	=> array(
				'template_id'      	=> $this->template_prefix .'36',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_36.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-grid/',
			),
			37 	=> array(
				'template_id'      	=> $this->template_prefix .'37',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Grid Overlay',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_37.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-grid-overlay/',
			),
			/*38 	=> array(
				'template_id'      	=> $this->template_prefix .'38',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Masonry',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_38.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-masonry/',
			),*/
			39 	=> array(
				'template_id'      	=> $this->template_prefix .'39',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Metro',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_39.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-metro/',
			),
			40 	=> array(
				'template_id'      	=> $this->template_prefix .'40',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Metro Overlay',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_40.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-metro-overlay/',
			),
			41 	=> array(
				'template_id'      	=> $this->template_prefix .'41',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog Classic',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_41.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-classic/',
			),
			42 	=> array(
				'template_id'      	=> $this->template_prefix .'42',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Blog List',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_42.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog-list/',
			),
			43 	=> array(
				'template_id'      	=> $this->template_prefix .'43',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Education Event - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_43.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',

				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/',
			),
			44 	=> array(
				'template_id'      	=> $this->template_prefix .'44',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Education Event - Speakers',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_44.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('speakers'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/speakers/',
			),
			45 	=> array(
				'template_id'      	=> $this->template_prefix .'45',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Education Event - Single Speaker',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_45.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('speakers'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/speaker/john-doeer/',
			),
			46 	=> array(
				'template_id'      	=> $this->template_prefix .'46',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Education Event - Agenda',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_46.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('agenda'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/agenda/',
			),
			47 	=> array(
				'template_id'      	=> $this->template_prefix .'47',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Multi Events - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_47.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/',
			),
			48 	=> array(
				'template_id'      	=> $this->template_prefix .'48',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Multi Events - Find Events',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_48.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('events'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/find-events/',
			),
			49 	=> array(
				'template_id'      	=> $this->template_prefix .'49',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Multi Events - Blog',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_49.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('blog'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/blog/',
			),
			50 	=> array(
				'template_id'      	=> $this->template_prefix .'50',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference Multi Events - 404 Not Found',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_50.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('404'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/404/',
			),
			51 	=> array(
				'template_id'      	=> $this->template_prefix .'51',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference City Events - Home',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_51.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('home'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/city-events/',
			),
			52 	=> array(
				'template_id'      	=> $this->template_prefix .'52',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference City Events - Discover The City',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_52.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('discover'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/city-events/discover-the-city/',
			),
			53 	=> array(
				'template_id'      	=> $this->template_prefix .'53',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference City Events - Contact',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_53.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'page',
				'subtype'			=> 'page',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('contact'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/city-events/contact/',
			),
						
			//Adding navigation menu block templates
			501 => array(
				'template_id'      	=> $this->template_prefix .'501',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Classic | Header 1',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_501.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/header/header-1/',
			),
			502 => array(
				'template_id'      	=> $this->template_prefix .'502',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Classic | Header 2',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_502.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/header/header-2/',
			),
			503 => array(
				'template_id'      	=> $this->template_prefix .'503',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_503.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/header/header/',
			),
			504 => array(
				'template_id'      	=> $this->template_prefix .'504',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_504.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/header/header/',
			),
			505 => array(
				'template_id'      	=> $this->template_prefix .'505',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Tech Forum | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_505.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/grandtech/header/header/',
			),
			506 => array(
				'template_id'      	=> $this->template_prefix .'506',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Digital Event | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_506.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/digital/header/header/',
			),
			507 => array(
				'template_id'      	=> $this->template_prefix .'507',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Business Event | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_507.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/business/header/header/',
			),
			508 => array(
				'template_id'      	=> $this->template_prefix .'508',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Conference | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_508.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/design/header/header/',
			),
			509 => array(
				'template_id'      	=> $this->template_prefix .'509',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Awards | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_509.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/awards/header/header/',
			),
			510 => array(
				'template_id'      	=> $this->template_prefix .'510',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Education Event | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_510.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/blog/header/header/',
			),
			511 => array(
				'template_id'      	=> $this->template_prefix .'511',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Multi Events | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_511.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/header/header/',
			),
			512 => array(
				'template_id'      	=> $this->template_prefix .'512',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - City Events | Header',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_512.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme navigation menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('navigation'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/city-events/header/header/',
			),
			
			//Adding mega menu block templates
			/*601 => array(
				'template_id'      	=> $this->template_prefix .'601',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Mega Menu Home Grid',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_601.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/megamenu/demo-mega-menu/',
			),
			602 => array(
				'template_id'      	=> $this->template_prefix .'602',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Mega Menu Page',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_602.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/megamenu/page-mega-menu/',
			),
			603 => array(
				'template_id'      	=> $this->template_prefix .'603',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Mega Menu Shop',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_603.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/megamenu/shop-mega-menu/',
			),
			/*604 => array(
				'template_id'      	=> $this->template_prefix .'604',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Mega Menu Pages',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_604.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/megamenu/pages-mega-menu/',
			),
			605 => array(
				'template_id'      	=> $this->template_prefix .'605',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Mega Menu Portfolio',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_605.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme mega menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('megamenu'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/megamenu/portfolio-mega-menu/',
			),*/
			
			//Adding footer block templates
			701 => array(
				'template_id'      	=> $this->template_prefix .'701',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Classic | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_701.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/footer/footer-1/',
			),
			702 => array(
				'template_id'      	=> $this->template_prefix .'702',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_702.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/footer/footer/',
			),
			703 => array(
				'template_id'      	=> $this->template_prefix .'703',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - VR Event | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_703.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/vr/footer/footer/',
			),
			704 => array(
				'template_id'      	=> $this->template_prefix .'704',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Tech Forum | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_704.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/grandtech/footer/footer/',
			),
			705 => array(
				'template_id'      	=> $this->template_prefix .'705',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Digital Event | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_705.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/digital/footer/footer/',
			),
			706 => array(
				'template_id'      	=> $this->template_prefix .'706',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Business Event | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_706.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/business/footer/footer/',
			),
			707 => array(
				'template_id'      	=> $this->template_prefix .'707',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Conference | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_707.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/design/footer/footer/',
			),
			708 => array(
				'template_id'      	=> $this->template_prefix .'708',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Design Awards | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_708.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',

				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/awards/footer/footer/',
			),
			709 => array(
				'template_id'      	=> $this->template_prefix .'709',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Education Event | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_709.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/blog/footer/footer/',
			),
			710 => array(
				'template_id'      	=> $this->template_prefix .'710',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Multi Events | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_710.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/multi-events/footer/footer/',
			),
			711 => array(
				'template_id'      	=> $this->template_prefix .'711',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - City Events | Footer',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_711.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme footer',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('footer'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/city-events/footer/footer/',
			),
			
			//Adding fullscreen menu block templates
			801 => array(
				'template_id'      	=> $this->template_prefix .'801',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Classic | Fullscreen Menu ',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_801.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/blog/fullmenu/home-business-forum/',
			),
			802 => array(
				'template_id'      	=> $this->template_prefix .'802',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Music Event | Fullscreen Menu ',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_802.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1646207582 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',

				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconference.themegoods.com/v5/music/fullmenu/default-fullscreen-menu/',
			),
			803 => array(
				'template_id'      	=> $this->template_prefix .'803',
				'source'            => $this->get_id(),
				'title'             => 'Grand Conference - Education Event | Mobile Menu ',
				'thumbnail'         => 'https://assets.themegoods.com/demo/grandconference/templates/screenshots/grandconference_803.jpg',
				'date'      		=> date( get_option( 'date_format' ), 1704883438 ),
				'type'				=> 'block',
				'subtype'			=> 'theme fullscreen menu',
				'author'            => 'ThemeGoods',
			
				'keywords'          => array('fullscreen'),
				'is_pro'            => false,
				'has_page_settings' => false,
				'url'               => 'https://grandconferencev5-2.themegoods.com/blog/fullmenu/mobile-menu/',
			),
		);
		
		if ( ! empty( $templates_data ) ) {
			foreach ( $templates_data as $template_data ) 
			{
				$templates_data['popularityIndex'] = 260;
				$templates_data['trendIndex'] = 125;
				
				$templates[] = $this->get_item( $template_data );
			}
		}

		if ( ! empty( $args ) ) {
			$templates = wp_list_filter( $templates, $args );
		}
		
		return $templates;
	}
	
	public function get_item( $template_data ) {
		return array(
			'template_id'     => $template_data['template_id'],
			'source'          => 'remote',
			'type'            => $template_data['type'],
			'subtype'         => $template_data['subtype'],
			'title'           => $template_data['title'],
			'thumbnail'       => $template_data['thumbnail'],
			'date'            => $template_data['date'],
			'author'          => $template_data['author'],
			'tags'            => $template_data['keywords'],
			'isPro'           => ( 1 == $template_data['is_pro'] ),
			'popularityIndex' => 260,
			'trendIndex'      => 125,
			'hasPageSettings' => 1,
			'url'             => $template_data['url'],
			'favorite'        => 0,
			'accessLevel'     => 0,
		);
	}

	public function save_item( $template_data ) {
		return false;
	}

	public function update_item( $new_data ) {
		return false;
	}

	public function delete_template( $template_id ) {
		return false;
	}

	public function export_template( $template_id ) {
		return false;
	}

	public function get_data( array $args, $context = 'display' ) {
		$url	  = 'https://assets.themegoods.com/demo/grandconference/templates/json/'.$args['template_id'].'.json';
		$response = wp_remote_get( $url, array( 'timeout' => 60 ) );
		$body     = wp_remote_retrieve_body( $response );
		$body     = json_decode( $body, true );
		$data     = ! empty( $body['content'] ) ? $body['content'] : false;
		
		$result = array();

		$result['content']       = $this->replace_elements_ids($data);
		$result['content']       = $this->process_export_import_content( $result['content'], 'on_import' );
		$result['page_settings'] = array();

		return $result;
	}
}
